spring.application.name=DA-Demo1-Monolith
spring.datasource.url=jdbc:h2:file:./data/fooddeliverymonolith;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=h2user
spring.datasource.password=h2pass

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
